"""updated

Revision ID: 5ba93cf054ca
Revises: fff97f0de61a
Create Date: 2024-07-19 11:59:45.818398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba93cf054ca'
down_revision = 'fff97f0de61a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('booking_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
